{% set name = "napari-obj" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-obj-{{ version }}.tar.gz
  sha256: 6ba507183ac93a4364904b899e76f78a1df0aa1e7900987773d876101b62279d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8

test:
  imports:
    - napari_obj
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/guignardlab/napari-obj
  summary: A plugin to read .obj files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
